import React, { ReactNode } from 'react';
import type { Metadata } from 'next';

import '@theme/scss/globals.scss';
import 'react-loading-skeleton/dist/skeleton.css';

import { AppProviders } from '@/shared/config/providers';
import Body from '@/shared/ui/components/Body/Body';
import Layout from '@/shared/ui/components/Layout/Layout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='ru'>
			<Body>
				<AppProviders>
					<Layout>{children}</Layout>
				</AppProviders>
			</Body>
		</html>
	);
}
